# Generated by Django 5.0.6 on 2024-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estudiante_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
