# Generated by Django 5.0.6 on 2024-08-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estudiante_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel_actual',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='puntos',
        ),
    ]
