# Generated by Django 5.0.6 on 2024-06-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_actual',
            field=models.IntegerField(default=1),
        ),
    ]
