# Generated by Django 5.0.6 on 2024-08-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_estudiante_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id_problema', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], max_length=10)),
                ('tema', models.CharField(max_length=100)),
            ],
        ),
    ]
