# Generated by Django 5.0.6 on 2024-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_codingproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='lenguaje',
            field=models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java')], default='python', max_length=10),
            preserve_default=False,
        ),
    ]
