# Generated by Django 5.0.6 on 2024-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_codingproblem_lenguaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
