# Generated by Django 5.0.6 on 2024-08-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_estudiante_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='puntos',
        ),
    ]
