# Generated by Django 5.0.6 on 2024-08-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_remove_estudiante_puntos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
