# Generated by Django 5.0.6 on 2025-05-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_nombre_estudiante_nombre_completo_and_more'),
        ('playground', '0007_delete_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestasPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestasRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.encuestaspreguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Monitorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemasDeProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], max_length=10)),
                ('tema', models.CharField(max_length=100)),
                ('lenguaje', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemasResueltos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.CharField(max_length=500)),
                ('solucion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.problemasdeprogramacion')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='CodingProblem',
        ),
    ]
