# Generated by Django 5.0.6 on 2025-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_encuestaspreguntas_encuestasrespuestas_monitorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaspreguntas',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='encuestaspreguntas',
            name='opciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='encuestaspreguntas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('opcion_multiple', 'Opción Múltiple'), ('texto_abierto', 'Texto Abierto'), ('checkbox', 'Checkbox')], max_length=50, null=True),
        ),
    ]
